version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/node-py23:node14.21.3-py2.7.16-py3.7.4
    environment:
    steps:
      - checkout
      - run:
          name: System information
          command: |
            python3 --version
            pip3 --version
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - restore_cache:
          keys:
            - v1-{{ arch }}-{{ checksum "server/requirements.txt" }}-{{ checksum "frontend/yarn.lock" }}
            - v1-{{ arch }}-{{ checksum "server/requirements.txt" }}
            - v1-{{ arch }}
      - run:
          name: Install dependencies (Python)
          command: |
            pip3 install -q -r requirements.txt \
              --index-url https://repo.fury.io/emoji-gen/ --extra-index-url https://pypi.org/simple
          working_directory: server
      - run:
          name: Install dependencies (Node)
          command: yarn
          working_directory: frontend
      - run:
          name: Test (Node)
          command: |
            yarn test
            yarn run build
          working_directory: frontend
      - run:
          name: Check git dirty
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./common/script/is-git-dirty.sh
            fi
      - save_cache:
          key: v1-{{ arch }}-{{ checksum "server/requirements.txt" }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/workspace/frontend/node_modules
            - ~/.cache/yarn/
            - ~/.cache/pip/
      - run:
          name: Notify test failed
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              pip3 install -q slackweb
              python3 common/script/notify.py failed
            fi
          when: on_fail
