/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Font_pb = require('./Font_pb.js');
goog.exportSymbol('proto.emoji.proto.InitialState', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.emoji.proto.InitialState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.emoji.proto.InitialState.repeatedFields_, null);
};
goog.inherits(proto.emoji.proto.InitialState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.emoji.proto.InitialState.displayName = 'proto.emoji.proto.InitialState';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.emoji.proto.InitialState.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.emoji.proto.InitialState.prototype.toObject = function(opt_includeInstance) {
  return proto.emoji.proto.InitialState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.emoji.proto.InitialState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.emoji.proto.InitialState.toObject = function(includeInstance, msg) {
  var f, obj = {
    fontsList: jspb.Message.toObjectList(msg.getFontsList(),
    Font_pb.Font.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.emoji.proto.InitialState}
 */
proto.emoji.proto.InitialState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.emoji.proto.InitialState;
  return proto.emoji.proto.InitialState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.emoji.proto.InitialState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.emoji.proto.InitialState}
 */
proto.emoji.proto.InitialState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Font_pb.Font;
      reader.readMessage(value,Font_pb.Font.deserializeBinaryFromReader);
      msg.addFonts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.emoji.proto.InitialState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.emoji.proto.InitialState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.emoji.proto.InitialState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.emoji.proto.InitialState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFontsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      Font_pb.Font.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Font fonts = 1;
 * @return {!Array.<!proto.emoji.proto.Font>}
 */
proto.emoji.proto.InitialState.prototype.getFontsList = function() {
  return /** @type{!Array.<!proto.emoji.proto.Font>} */ (
    jspb.Message.getRepeatedWrapperField(this, Font_pb.Font, 1));
};


/** @param {!Array.<!proto.emoji.proto.Font>} value */
proto.emoji.proto.InitialState.prototype.setFontsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.emoji.proto.Font=} opt_value
 * @param {number=} opt_index
 * @return {!proto.emoji.proto.Font}
 */
proto.emoji.proto.InitialState.prototype.addFonts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.emoji.proto.Font, opt_index);
};


proto.emoji.proto.InitialState.prototype.clearFontsList = function() {
  this.setFontsList([]);
};


goog.object.extend(exports, proto.emoji.proto);
